import Head from "next/head";
// import Image from "next/image";
import styles from "../styles/Home.module.css";
import Link from "next/link";
// import Dummy from "./component/dummy";

export default function Home() {
  return (
    <div className={styles.container}>
      <style jsx>
        {`
            h2{
              font-size:20px;
            }
            h3{
              font-size:38px;
            }
        `}
      </style>
      {/* <Dummy/> */}
      <Head>
        <title>Hunting Coder</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Hunting Coder</h1>

        <div className={styles.divwraper}>
        {/* <Image className={styles.homeimg} src="/Home.avif" width={400} height={233} /> */}
        <img className={styles.homeimg} src="/Home.avif" width={350} height={233} alt="hunting coder" />
        </div>
        <p className={styles.description}>let`s make Coding easy for everyone!</p>
        <div className="blog">
          <h2>Popular Blog</h2>
          <div className="blogItem">
            <h3>Is JavaScript Powerfull</h3>
            <p>JavaScript is used to write a logic for web and its help to give functionality to 
              user
            </p>
          </div>
          <div className="blogItem">
            <h3>Is JavaScript is good for Gaming?</h3>
            <p>JavaScript is used to write a logic for web. You can use javaScript as a scripting |
              for gaming and javaScript is after the C# most recommonded language in that time..
            </p>
          </div>
     
        </div>
      </main>

      <footer className={styles.footer}>
       
      </footer>
    </div>
  );
}
