import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Link from "next/link";
// import Dummy from "./component/dummy";

export default function Home() {
  return (
    <div className={styles.container}>
      <style jsx>
        {`
            h2{
              font-size:20px;
            }
            h3{
              font-size:38px;
            }
        `}
      </style>
      {/* <Dummy/> */}
      <Head>
        <title>Hunting Coder</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Hunting Coder</h1>

        <div className={styles.divwraper}>
        <Image className={styles.homeimg} src="/Home.avif" width={400} height={233} />
        </div>
        <p className={styles.description}>let`s make Coding easy for everyone!</p>
        <div className="blog">
          <h2>Popular Blog</h2>
          <div className="blogItem">
            <h3>JavaScript</h3>
            <p>JavaScript is used to write a logic for web</p>
          </div>
          <div className="blogItem">
            <h3>JavaScript</h3>
            <p>JavaScript is used to write a logic for web</p>
          </div>
          <div className="blogItem">
            <h3>JavaScript</h3>
            <p>JavaScript is used to write a logic for web</p>
          </div>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}
