import Head from "next/head";
// import Image from "next/image";
import styles from "../styles/Home.module.css";
import Link from "next/link";
// import Dummy from "./component/dummy";

export default function Home() {
  return (
    <div className={styles.container}>
      {/* <style jsx>
        {`
            h2{
              font-size:20px;
            }
            h3{
              font-size:38px;
            }
        `}
      </style> */}
      {/* <Dummy/> */}
      <Head>
        <title>Hunting Coder</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div className={styles.divwraper}>
          {/* <Image className={styles.homeimg} src="/Home.avif" width={400} height={233} /> */}
          <img
            className={styles.homeimg}
            src="/Home.avif"
            width={237}
            height={158}
            alt="hunting coder"
          />
        </div>
        <span><h1 className={styles.title}>&lt;HuntingCoder/&gt;</h1></span>
        <div>
          <h2 className={styles.h2}>Popular Blog</h2>
        
          <div className="blogItem">
            <h3 className={styles.h3}>Is JavaScript Can used to be a gaming</h3>
            <p className={styles.p}> 
              JavaScript is used to write a logic for web and its help to give
              functionality to user</p>
              <button className={styles.btn}>Read More</button>
          </div>
          <div className="blogItem">
            <h3 className={styles.h3}>Is JavaScript Powerfull for webDevelopment</h3>
            <p className={styles.p}>
              JavaScript is used to write a logic for web and its help to give
              functionality to user
            </p>
              <button className={styles.btn}>Read More</button>
          </div>
          <div className="blogItem">
            <h3 className={styles.h3}>Is JavaScript Powerfull in 2022</h3>
            <p className={styles.p}>
              JavaScript is used to write a logic for web and its help to give
              functionality to user 
            </p>
              <button className={styles.btn}>Read More</button>
            </div>
          </div>
      </main>

      <footer className={styles.footer}></footer>
    </div>
  );
}
